# Generated by Django 4.1.7 on 2023-04-29 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0006_tag_post_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.TextField(max_length=64, unique=True),
        ),
    ]
