# Generated by Django 4.1.7 on 2023-04-29 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("first", "0007_alter_tag_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
